# Generated by Django 5.2.10 on 2026-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
